port: /dev/ttyUSB0
baud: 115200
rate: 20
sync_write: True
sync_read: True
read_rate: 20
write_rate: 20

joints: {
    head_pan_joint: {id: 1, neutral: 512, max_speed: 100, min_angle: -145, max_angle: 145, invert: False},
    head_tilt_joint: {id: 2, neutral: 512, max_speed: 100, min_angle: -90, max_angle: 90, invert: False}
}

controllers: {
   #  Pololu motors: 1856 cpr = 0.3888105m travel = 4773 ticks per meter (empirical: 4100)
   base_controller: {type: diff_controller, base_frame_id: base_footprint, base_width: 0.26, ticks_meter: 4100, Kp: 12, Kd: 12, Ki: 0, Ko: 50, accel_limit: 1.0},
   head_controller: {type: 'follow_controller', joints: [head_pan_joint, head_tilt_joint], action_name: head_controller/follow_joint_trajectory, onboard: True}
}
