local_costmap:
   global_frame: odom
   #global_frame: /odom_combined
   robot_base_frame: base_footprint
   update_frequency: 3.0
   publish_frequency: 1.0
   #static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.05
   transform_tolerance: 1.2
   #map_type: costmap

   plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
