#! /usr/bin/env python

import sys
import rospy

import world_canvas_server
#import warehouse_ros_mongo

if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'true':
        # Only (optional) argument is a debug='true'/'false' flag
        rospy.init_node('world_canvas_server', log_level=rospy.DEBUG)
    else:
        rospy.init_node('world_canvas_server')

    world_canvas_server.AnnotationsServer()
  
    rospy.spin()
