RobotSimNode:
  ros__parameters:
    wheels:
      separation: 0.160
      radius: 0.033
      lx: 0.17
      ly: 0.195

    joint_states_frame: "base_footprint"
    odom_frame: "odom"               #里程计坐标系
    base_frame: "base_footprint"      #底盘坐标系

    control_rate: 100                #底盘控制频率  
